services:
  db:
    image: postgres:16
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./mockup-data.sql:/docker-entrypoint-initdb.d/data.sql
      - ./backup:/var/backup

  node:
    build: .
    ports:
      - "9001:8081"
    env_file:
      - .env
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "9002:8082"
    env_file:
      - .env
    environment:
      - PGADMIN_LISTEN_PORT=8082
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
      - PGADMIN_DEFAULT_EMAIL=dev@badgehub.team
      - PGADMIN_DEFAULT_PASSWORD=badgehub
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json

volumes:
  postgres_data:
  pgadmin_data:
