packages:
  - 'packages/*'

overrides:
  esbuild: ^0.27.7

hoistPattern:
  - 'zod'
  - '@orpc/*'

dedupePeerDependents: true

minimumReleaseAge: 4320

allowBuilds:
  '@scarf/scarf': true
  cpu-features: true
  esbuild: true
  lefthook: true
  sharp: true
  ssh2: true
